version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/
    overwrite: true
file_exists_behavior: OVERWRITE
branch_config:
    main:
        deploymentGroupName: ztd-deployment-group
        deploymentGroupConfig:
            serviceRoleArn: arn:aws:iam::XXXXXXX:role/CodeDeployTestApplication
